### ISSUE TITLE
Bug in order_gfa after merging PR14

### ISSUE THREAD

**Issue by tobiasmarschall** [marschall-lab/gaftools#15]
I get the following error in `order_gfa`:

```
$ gaftools order_gfa --chromosome_order chr1 test.gfa
Reading test.gfa
Reading test.gfa
The graph has:
The graph has 90015 Nodes and 129941 Edges
Connected components: 1
Found one connected component per expected chromosome.
Processing chr1
 Input graph: 90015 nodes
 Finding Biconnected Components of the component
Traceback (most recent call last):
  File "/home/tobi/miniforge3/envs/gaftools-dev/bin/gaftools", line 8, in <module>
    sys.exit(main())
  File "/home/tobi/scm/gaftools/gaftools/__main__.py", line 88, in main
    module.main(args)
  File "/home/tobi/scm/gaftools/gaftools/cli/order_gfa.py", line 217, in main
    run_order_gfa(**vars(args))
  File "/home/tobi/scm/gaftools/gaftools/cli/order_gfa.py", line 56, in run_order_gfa
    scaffold_nodes, inside_nodes, node_order, bo, bubble_count = decompose_and_order(graph, component_nodes, bo)
  File "/home/tobi/scm/gaftools/gaftools/cli/order_gfa.py", line 136, in decompose_and_order
    scaffold_graph.add_edge(('s',node1), ('s',node2))
TypeError: add_edge() missing 2 required positional arguments: 'node2' and 'node2_dir'
```

The error does not happen in commit b286340facf1168eaaff4294bd5e973867a7458d. Also finding biconnected components seems to be quite a bit slower now after the merge.

**Comment by tobiasmarschall** [comment]
I've pushed the graph that causes this to `tests/data/large-graph-chr1.gfa.gz`

**Comment by tobiasmarschall** [comment]
Further note: The number of edges being counted by `order_gfa` seems to be different now. It was in version b286340facf1168eaaff4294bd5e973867a7458d :
```
Reading minigraph-extended_all-Oct24-ordered/minigraph-extended_all-Oct24-chr1.gfa
Nodes: 90015
Edges: 129939
Connected components: 1
Found one connected component per expected chromosome.
Processing chr1
  Input graph: 90015 nodes
  Bubbles: 17942
  Scaffold graph: 35887 nodes
Total bubbles: 17942
```

**Comment by tobiasmarschall** [comment]
It actually seems that the old version was wrong and did not properly account for the direction of edges:
```
$ grep -E '^L' test.gfa |cut -f 1-5|sort |uniq |wc -l
129941
$ grep -E '^L' test.gfa |cut -f 1,2,4|sort |uniq |wc -l
129939
```

**Comment by tobiasmarschall** [comment]
@samarendra-pani 
```
$ grep -E '^L' test.gfa |cut -f 1,2,4|sort |uniq -D
L       s13938  s13939
L       s13938  s13939
L       s13939  s13940
L       s13939  s13940
```

**Comment by tobiasmarschall** [comment]
![image](https://github.com/marschall-lab/gaftools/assets/1032740/4ea4dc0b-78ed-43c5-b6ba-9e1a37537ca2)

**Comment by fawaz-dabbaghieh** [comment]
I fixed the bug and pushed the fixes to main under [3120e44](https://github.com/marschall-lab/gaftools/commit/3120e44afd3c6e1e8e69c997b4674deb2718fd54) commit.
The file `tests/data/large-graph-chr1.gfa.gz` seems to already contain bubble information, and I compared the output file I got with this input file and they were identical.

Now I need to investigate why finding biconnected components is taking too long, I'll profile the code and get back to you on that, as I used the same Networkx algorithm, so not sure where all the extra time is coming from.

**Comment by tobiasmarschall** [comment]
@fawaz-dabbaghieh thanks for taking a look, but that didn't fix it for me, unfortunately (running commit 3120e44afd3c6e1e8e69c997b4674deb2718fd54):

```
gaftools order_gfa --outdir out_3120e44 minigraph-extended_all-Oct24.gfa 
Reading minigraph-extended_all-Oct24.gfa
The graph has:
The graph has 1250314 Nodes and 1802130 Edges
Connected components: 25
Found one connected component per expected chromosome.
Processing chr1
 Input graph: 90015 nodes
 Finding Biconnected Components of the component
 It took 174.59428897401085 seconds to find the Biconnected Components
  Bubbles: 0
  Scaffold graph: 0 nodes
Traceback (most recent call last):
  File "/home/tobi/miniforge3/envs/gaftools-dev/bin/gaftools", line 8, in <module>
    sys.exit(main())
  File "/home/tobi/scm/gaftools/gaftools/__main__.py", line 88, in main
    module.main(args)
  File "/home/tobi/scm/gaftools/gaftools/cli/order_gfa.py", line 224, in main
    run_order_gfa(**vars(args))
  File "/home/tobi/scm/gaftools/gaftools/cli/order_gfa.py", line 56, in run_order_gfa
    scaffold_nodes, inside_nodes, node_order, bo, bubble_count = decompose_and_order(graph, component_nodes, bo)
  File "/home/tobi/scm/gaftools/gaftools/cli/order_gfa.py", line 159, in decompose_and_order
    assert len(degree_one) == 2
AssertionError
```

**Comment by tobiasmarschall** [comment]
Could you first create a test case that triggers the bug? On another note, I'm not clear what this is doing: https://github.com/marschall-lab/gaftools/blob/3120e44afd3c6e1e8e69c997b4674deb2718fd54/gaftools/cli/order_gfa.py#L81
Looks like all `L` line from the input are being copied to all output files, is that intentional? Also, I think parsing stuff should now live in GFA.py.

**Comment by fawaz-dabbaghieh** [comment]
@tobiasmarschall  You are running it here for another file, right? It looks like another bug you're getting this time, but for me, the first bug you encountered has been fixed.

I don't see this file `minigraph-extended_all-Oct24.gfa` anywhere in the test data. For the `large-graph-chr1.gfa.gz`, this is what I'm getting when I run it:
```
gaftools order_gfa --outdir out/ large-graph-chr1.gfa.gz  --chromosome_order chr1
Reading large-graph-chr1.gfa.gz
The graph has:
The graph has 90015 Nodes and 129941 Edges
Connected components: 1
Found one connected component per expected chromosome.
Processing chr1
 Input graph: 90015 nodes
 Finding Biconnected Components of the component
 It took 86.29989153799943 seconds to find the Biconnected Components
  Bubbles: 17942
  Scaffold graph: 35887 nodes
Total bubbles: 17942
```
So could you point me to this file you're testing so I can check where the bug is. Moreover, has this file been tested also on the old version of `gaftools`, if yes, are the results somewhere so I can compare them?


As for the second issue about parsing the GFA. Yes, this is not an ideal code but this needs a longer discussion maybe. The problem stems from the fact that my GFA class encodes each edge in both directions, so when I write the GFA out using its internal writing functions, it will represent each edge twice, once in the forward direction and once in the backward direction. So, the GFA class won't know what was in the original file anymore and it will output both, and this would mess with the other tests that have been implemented.
So this needs to be discussed I think at some point.
Reasons it's done like this, with other GFAs I worked with, this is how it has been represented, for example MBGs graph outputs are like this, the edge would have two L lines, for each direction.

**Comment by tobiasmarschall** [comment]
Yes, I know ran for the full file, previous I had extracted one chromosome to make a smaller example. The full file is in Hilbert: `/gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/extend-graph-by-callsets/results-population-calls-Oct24/minigraph/minigraph-extended_all.gfa`
It runs fine on commit b286340facf1168eaaff4294bd5e973867a7458d I have the results, but am on a very slow Wifi right now and cannot upload. But it runs in a few minutes.

**Comment by tobiasmarschall** [comment]
For the second issue regarding the `L` lines, could you open a separate issue for this? One thing we have to make sure here is that not all `L` lines get written into every output file. This would defeat the purpose of splitting them.

**Comment by fawaz-dabbaghieh** [comment]
OK! I'll look into the full file and get back to you, to see what's going on. Would be also good to profile my code on the big file to see why is it slow.
About the `L` lines, let me discuss this with Samarandra and Arda tomorrow, maybe I am also a bit confused about things and we can come to some agreement.
I'll keep you updated :)

**Comment by fawaz-dabbaghieh** [comment]
I still haven't looked at the last bug you were getting, but spent some time using `line_profiler` to find out why the code was slow. I was able to improve the run time significantly. For the large graph in the test data, the time went down from over 200 elapsed seconds to 20.
I will look into the bug you were getting next and get back to you

**Comment by fawaz-dabbaghieh** [comment]
I just pushed a commit that seems to fix the bug, I am not 100% sure what happened with that bug, but I fixed another issue I found in the code and this one got fixed along with it :)
I also improved the runtime significantly, `line_profiler` pointed me out to a couple of big problems in the codes that were relatively easy to fix, now finding biconnected components and ordering the scaffold graph runs very fast. It took for example 1:37 elapsed time to run `gaftools` on the minigraph graph.

**Comment by tobiasmarschall** [comment]
Thanks, @fawaz-dabbaghieh. I just tried it and it ran fine for me. Could you clean up the code that you left commented out? One other thing I realized is that it'd be nice to actually output all the nodes in their proper order according to `BO` and `NO` tags. But for now that'd just be a cosmetic change and is not so important. I'll create another issue with this for later.

**Comment by tobiasmarschall** [comment]
Unfortunately, the csv files are broken. Example how a line looked before (commit b286340):
```
s70916,blue,chr1,121521495,17698,3
```
and after (commit bebc819d):
```
s70916,blue,('Z', 'chr1'),('i', '121521495'),17698,3
```

@fawaz-dabbaghieh I think it is really important to add test cases now. This is too trail-and-error right now.

**Comment by fawaz-dabbaghieh** [comment]
I'll fix it.
Yes, order graph needs better tests now, I'll work on it.

**Comment by fawaz-dabbaghieh** [comment]
I think the bugs have been fixed now, at least I hope so :)

**Comment by tobiasmarschall** [comment]
Thanks, @fawaz-dabbaghieh! I can confirm it works for me (and runs quickly). Thanks for also for expanding the test case.
